services:
  kontrakan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kontrakan-app
    ports:
      - "4001:4001"
    env_file:
      - .env.local
    restart: unless-stopped
