services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: kontrakan-backend
    restart: always
    ports:
      # Expose ke port 3000 host (127.0.0.1 agar aman hanya bisa diakses Nginx internal)
      - "127.0.0.1:3000:3000"
    env_file:
      - ./Backend/.env
    environment:
      - NODE_ENV=production
      - PORT=3000
